# Generated by Django 3.2.18 on 2023-03-16 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allergens',
            name='allergen',
            field=models.CharField(choices=[('None', 'None'), ('Vegan', 'Vegan'), ('Vegetarian', 'Vegetarian'), ('Gluten-free', 'Gluten-free'), ('Contains nuts', 'Contains nuts'), ('Dairy-free', 'Dairy-free')], max_length=50),
        ),
        migrations.AlterField(
            model_name='mainingredient',
            name='main_ingredient_name',
            field=models.CharField(choices=[('Chicken', 'Chicken'), ('Noodles', 'Noodles'), ('Fish', 'Fish'), ('Beef', 'Beef'), ('Fruit', 'Fruit'), ('Pork', 'Pork'), ('Rice', 'Rice'), ('Seafood', 'Seafood'), ('Potato', 'Potato'), ('Bread', 'Bread'), ('Vegetables', 'Vegetables'), ('Eggs', 'Eggs'), ('Oats', 'Oats')], max_length=50),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='allergens',
            field=models.ManyToManyField(choices=[('None', 'None'), ('Vegan', 'Vegan'), ('Vegetarian', 'Vegetarian'), ('Gluten-free', 'Gluten-free'), ('Contains nuts', 'Contains nuts'), ('Dairy-free', 'Dairy-free')], to='recipes.Allergens'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='main_ingredient',
            field=models.ManyToManyField(choices=[('Chicken', 'Chicken'), ('Noodles', 'Noodles'), ('Fish', 'Fish'), ('Beef', 'Beef'), ('Fruit', 'Fruit'), ('Pork', 'Pork'), ('Rice', 'Rice'), ('Seafood', 'Seafood'), ('Potato', 'Potato'), ('Bread', 'Bread'), ('Vegetables', 'Vegetables'), ('Eggs', 'Eggs'), ('Oats', 'Oats')], to='recipes.MainIngredient'),
        ),
    ]
