# Generated by Django 3.2.18 on 2023-03-15 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_ingredient_name', models.CharField(choices=[('Chicken', 'Chicken'), ('Noodles', 'Noodles'), ('Fish', 'Fish'), ('Beef', 'Beef'), ('Fruit', 'Fruit'), ('Pork', 'Pork'), ('Rice', 'Rice'), ('Seafood', 'Seafood'), ('Potato', 'Potato'), ('Bread', 'Bread'), ('Vegetables', 'Vegetables'), ('Eggs', 'Eggs')], max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.TextField(default='', null=True),
        ),
        migrations.DeleteModel(
            name='Ingredient',
        ),
        migrations.AddField(
            model_name='mainingredient',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_ingredient', to='recipes.recipe'),
        ),
    ]
