# Generated by Django 3.2.18 on 2023-03-15 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20230315_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='cooking_time',
            field=models.DurationField(choices=[(5, '5 mins'), (10, '10 mins'), (15, '15 mins'), (20, '20 mins'), (25, '25 mins'), (30, '30 mins'), (35, '35 mins'), (40, '40 mins'), (45, '45 mins'), (50, '50 mins'), (55, '55mins'), (60, '1 hour')], null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='prep_time',
            field=models.DurationField(choices=[(5, '5 mins'), (10, '10 mins'), (15, '15 mins'), (20, '20 mins'), (25, '25 mins'), (30, '30 mins'), (35, '35 mins'), (40, '40 mins'), (45, '45 mins'), (50, '50 mins'), (55, '55mins'), (60, '1 hour')], null=True),
        ),
    ]
