# Generated by Django 3.2.18 on 2023-03-17 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20230317_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allergens',
            name='allergen',
            field=models.CharField(choices=[('None', 'None'), ('Vegan', 'Vegan'), ('Vegetarian', 'Vegetarian'), ('Gluten-free', 'Gluten-free'), ('Contains nuts', 'Contains nuts'), ('Dairy-free', 'Dairy-free')], max_length=50),
        ),
        migrations.AlterField(
            model_name='mainingredient',
            name='main_ingredient_name',
            field=models.CharField(choices=[('Chicken', 'Chicken'), ('Noodles', 'Noodles'), ('Fish', 'Fish'), ('Beef', 'Beef'), ('Fruit', 'Fruit'), ('Pork', 'Pork'), ('Rice', 'Rice'), ('Seafood', 'Seafood'), ('Potato', 'Potato'), ('Bread', 'Bread'), ('Vegetables', 'Vegetables'), ('Eggs', 'Eggs'), ('Oats', 'Oats')], max_length=50),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='allergens',
            field=models.ForeignKey(choices=[('None', 'None'), ('Vegan', 'Vegan'), ('Vegetarian', 'Vegetarian'), ('Gluten-free', 'Gluten-free'), ('Contains nuts', 'Contains nuts'), ('Dairy-free', 'Dairy-free')], default=0, on_delete=django.db.models.deletion.CASCADE, to='recipes.allergens'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='main_ingredient',
            field=models.ForeignKey(choices=[('Chicken', 'Chicken'), ('Noodles', 'Noodles'), ('Fish', 'Fish'), ('Beef', 'Beef'), ('Fruit', 'Fruit'), ('Pork', 'Pork'), ('Rice', 'Rice'), ('Seafood', 'Seafood'), ('Potato', 'Potato'), ('Bread', 'Bread'), ('Vegetables', 'Vegetables'), ('Eggs', 'Eggs'), ('Oats', 'Oats')], default=0, on_delete=django.db.models.deletion.CASCADE, to='recipes.mainingredient'),
        ),
    ]
