# Generated by Django 3.2.18 on 2023-03-17 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0012_auto_20230317_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='dairy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recipe',
            name='eggs',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recipe',
            name='nuts',
            field=models.BooleanField(default=False),
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='allergens',
        ),
        migrations.AddField(
            model_name='recipe',
            name='allergens',
            field=models.IntegerField(choices=[(1, 'Vegan'), (2, 'Vegetarian')], default=0),
        ),
        migrations.DeleteModel(
            name='Allergens',
        ),
    ]
