# Generated by Django 3.2.18 on 2023-03-17 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0013_auto_20230317_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='allergens',
            field=models.IntegerField(choices=[(0, 'None'), (1, 'Vegan'), (2, 'Vegetarian')], default=0),
        ),
    ]
