# Generated by Django 3.2.18 on 2023-03-17 12:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0015_auto_20230317_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.DurationField(choices=[(datetime.timedelta(seconds=300), '5 mins'), (datetime.timedelta(seconds=600), '10 mins'), (datetime.timedelta(seconds=900), '15 mins'), (datetime.timedelta(seconds=1200), '20 mins'), (datetime.timedelta(seconds=1500), '25 mins'), (datetime.timedelta(seconds=1800), '30 mins'), (datetime.timedelta(seconds=2100), '35 mins'), (datetime.timedelta(seconds=2400), '40 mins'), (datetime.timedelta(seconds=2700), '45 mins'), (datetime.timedelta(seconds=3000), '50 mins'), (datetime.timedelta(seconds=3300), '55mins'), (datetime.timedelta(seconds=3600), '1 hour')], default=None),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='difficulty',
            field=models.IntegerField(choices=[(0, 'Easy-peasy'), (1, 'I know cooking'), (2, 'Up for a challenge'), (3, 'Battle hardened')], default=None),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='label',
            field=models.IntegerField(choices=[(0, 'None'), (1, 'Vegan'), (2, 'Vegetarian')], default=None),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='main_ingredient',
            field=models.IntegerField(choices=[(0, 'Chicken'), (1, 'Noodles'), (2, 'Fish'), (3, 'Beef'), (4, 'Fruit'), (5, 'Pork'), (6, 'Rice'), (7, 'Seafood'), (8, 'Potato'), (9, 'Bread'), (10, 'Vegetables'), (11, 'Eggs'), (12, 'Oats')], default=None),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='prep_time',
            field=models.DurationField(choices=[(datetime.timedelta(seconds=300), '5 mins'), (datetime.timedelta(seconds=600), '10 mins'), (datetime.timedelta(seconds=900), '15 mins'), (datetime.timedelta(seconds=1200), '20 mins'), (datetime.timedelta(seconds=1500), '25 mins'), (datetime.timedelta(seconds=1800), '30 mins'), (datetime.timedelta(seconds=2100), '35 mins'), (datetime.timedelta(seconds=2400), '40 mins'), (datetime.timedelta(seconds=2700), '45 mins'), (datetime.timedelta(seconds=3000), '50 mins'), (datetime.timedelta(seconds=3300), '55mins'), (datetime.timedelta(seconds=3600), '1 hour')], default=None),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='recipe_name',
            field=models.CharField(default=None, max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='type',
            field=models.IntegerField(choices=[(0, 'Breakfast'), (1, 'Lunch'), (2, 'Dinner'), (3, 'Snack')], default=None),
        ),
    ]
