# Generated by Django 3.2.18 on 2023-04-09 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0017_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='saved_recipes',
        ),
        migrations.AddField(
            model_name='recipe',
            name='saved',
            field=models.BooleanField(default=False),
        ),
    ]
