# Generated by Django 3.2.18 on 2023-04-14 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0019_auto_20230409_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='difficulty',
            field=models.IntegerField(choices=[(20, 'Easy & quick'), (40, 'Moderate'), (60, 'Intermediate'), (80, 'Challenging')], default=None),
        ),
    ]
