# Generated by Django 3.2.18 on 2023-04-17 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0021_remove_recipe_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='main_ingredient',
        ),
    ]
