# Generated by Django 3.2.18 on 2023-04-17 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0022_remove_recipe_main_ingredient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='label',
        ),
    ]
