# Generated by Django 3.2.18 on 2023-04-17 22:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0025_auto_20230417_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.DurationField(choices=[(datetime.timedelta(seconds=300), '5 mins'), (datetime.timedelta(seconds=600), '10 mins'), (datetime.timedelta(seconds=900), '15 mins'), (datetime.timedelta(seconds=1200), '20 mins'), (datetime.timedelta(seconds=1500), '25 mins'), (datetime.timedelta(seconds=1800), '30 mins'), (datetime.timedelta(seconds=2100), '35 mins'), (datetime.timedelta(seconds=2400), '40 mins'), (datetime.timedelta(seconds=2700), '45 mins'), (datetime.timedelta(seconds=3000), '50 mins'), (datetime.timedelta(seconds=3300), '55mins'), (datetime.timedelta(seconds=3600), '1 hour')]),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='difficulty',
            field=models.IntegerField(choices=[(20, 'Easy & quick'), (40, 'Moderate'), (60, 'Intermediate'), (80, 'Challenging')]),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='prep_time',
            field=models.DurationField(choices=[(datetime.timedelta(seconds=300), '5 mins'), (datetime.timedelta(seconds=600), '10 mins'), (datetime.timedelta(seconds=900), '15 mins'), (datetime.timedelta(seconds=1200), '20 mins'), (datetime.timedelta(seconds=1500), '25 mins'), (datetime.timedelta(seconds=1800), '30 mins'), (datetime.timedelta(seconds=2100), '35 mins'), (datetime.timedelta(seconds=2400), '40 mins'), (datetime.timedelta(seconds=2700), '45 mins'), (datetime.timedelta(seconds=3000), '50 mins'), (datetime.timedelta(seconds=3300), '55mins'), (datetime.timedelta(seconds=3600), '1 hour')]),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='recipe_name',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='type',
            field=models.IntegerField(choices=[(0, 'Breakfast'), (1, 'Lunch'), (2, 'Dinner'), (3, 'Snack')]),
        ),
    ]
