# Generated by Django 3.2.18 on 2023-04-17 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0028_remove_recipe_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='approved',
        ),
    ]
