# Generated by Django 3.2.18 on 2023-04-18 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0029_remove_comment_approved'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_on']},
        ),
        migrations.AlterField(
            model_name='recipe',
            name='difficulty',
            field=models.IntegerField(choices=[(20, 'Easy'), (40, 'Moderate'), (60, 'Intermediate'), (80, 'Challenging')]),
        ),
    ]
