# Generated by Django 3.2.18 on 2023-04-18 16:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0030_auto_20230418_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.DurationField(choices=[(datetime.timedelta(seconds=300), '0 mins'), (datetime.timedelta(seconds=300), '5 mins'), (datetime.timedelta(seconds=600), '10 mins'), (datetime.timedelta(seconds=900), '15 mins'), (datetime.timedelta(seconds=1200), '20 mins'), (datetime.timedelta(seconds=1500), '25 mins'), (datetime.timedelta(seconds=1800), '30 mins'), (datetime.timedelta(seconds=2100), '35 mins'), (datetime.timedelta(seconds=2400), '40 mins'), (datetime.timedelta(seconds=2700), '45 mins'), (datetime.timedelta(seconds=3000), '50 mins'), (datetime.timedelta(seconds=3300), '55mins'), (datetime.timedelta(seconds=3600), '1 hour')]),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='prep_time',
            field=models.DurationField(choices=[(datetime.timedelta(seconds=300), '0 mins'), (datetime.timedelta(seconds=300), '5 mins'), (datetime.timedelta(seconds=600), '10 mins'), (datetime.timedelta(seconds=900), '15 mins'), (datetime.timedelta(seconds=1200), '20 mins'), (datetime.timedelta(seconds=1500), '25 mins'), (datetime.timedelta(seconds=1800), '30 mins'), (datetime.timedelta(seconds=2100), '35 mins'), (datetime.timedelta(seconds=2400), '40 mins'), (datetime.timedelta(seconds=2700), '45 mins'), (datetime.timedelta(seconds=3000), '50 mins'), (datetime.timedelta(seconds=3300), '55mins'), (datetime.timedelta(seconds=3600), '1 hour')]),
        ),
    ]
