# Generated by Django 3.2.18 on 2023-04-25 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0031_auto_20230418_1633'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='dairy',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='nuts',
        ),
    ]
